config/routes.rb
Rails.application.routes.draw do
  resources :forms
  resources :validation_patterns do
    # TODO
    # resources :validation_patterns
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/form.rb
class Form < ApplicationRecord
end

app/models/validation_pattern.rb
class ValidationPattern < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :set_form, only: [:show, :edit, :update, :destroy]

  def index
    @forms = Form.all
  end

  def show
  end

  def new
    @form = Form.new
  end

  def edit
  end

  def create
    @form = Form.new(form_params)

    if @form.save
      redirect_to @form, notice: 'Form was successfully created.'
    else
      render :new
    end
  end

  def update
    if @form.update(form_params)
      redirect_to @form, notice: 'Form was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @form.destroy
    redirect_to forms_url, notice: 'Form was successfully destroyed.'
  end

  private

  def set_form
    @form = Form.find(params[:id])
  end

  def form_params
    params.require(:form).permit :active, :confirmation_url, :name, :trigger_frequency, :url
  end
end

app/controllers/validation_patterns_controller.rb
class ValidationPatternsController < ApplicationController
  before_action :set_validation_pattern, only: [:show, :edit, :update, :destroy]

  # GET /validation_patterns
  def index
    @validation_patterns = ValidationPattern.all
  end

  # GET /validation_patterns/1
  def show
  end

  # GET /validation_patterns/new
  def new
    @validation_pattern = ValidationPattern.new
  end

  # GET /validation_patterns/1/edit
  def edit
  end

  # POST /validation_patterns
  def create
    @validation_pattern = ValidationPattern.new(validation_pattern_params)

    if @validation_pattern.save
      redirect_to @validation_pattern, notice: 'Validation pattern was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /validation_patterns/1
  def update
    if @validation_pattern.update(validation_pattern_params)
      redirect_to @validation_pattern, notice: 'Validation pattern was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /validation_patterns/1
  def destroy
    @validation_pattern.destroy
    redirect_to validation_patterns_url, notice: 'Validation pattern was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_validation_pattern
      @validation_pattern = ValidationPattern.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def validation_pattern_params
      params.require(:validation_pattern).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def fingerprinted_asset name
    Rails.env.production? ? "#{name}-#{ASSET_FINGERPRINT}" : name
  end
end

app/helpers/validation_patterns_helper.rb
module ValidationPatternsHelper
end

app/views/forms/_form.html.slim
= form_for(form) do |f|
  - if form.errors.any?
    #error_explanation
      h2
        = pluralize(form.errors.count, 'error')
        |  prohibited this form from being saved:

      ul
        - form.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name

  .field
    = f.label :url
    = f.text_field :url

  .field
    = f.label :confirmation_url
    = f.text_field :confirmation_url

  .field
    = f.label :active
    = f.check_box :active

  .field
    = f.label :trigger_frequency
    = f.text_field :trigger_frequency

  = f.submit

app/views/forms/edit.html.slim
header.header
  h1 Edit Form
  h2 Modify an existing form

main
  = render 'form', form: @form

.actions
  = link_to 'Show', @form
  = link_to 'Back', forms_path

app/views/forms/index.html.slim
p#notice = notice

header.header
  h1 Forms
  h2 Manage all forms

main
  .forms
    - @forms.each do |form|
      section.form
        .informations
          h1 = form.name
          a href="#{form.url}" = form.url

        .status
          = 'actived' if form.active

.actions
  = link_to 'Add', new_form_path, class: 'new-form-link'

/ table
/   thead
/     tr
/       th Name
/       th URL
/       th Confirmation URL
/       th Active
/       th colspan='3'

/   tbody
/     - @forms.each do |form|
/       tr
/         td = form.name
/         td = form.url
/         td = form.confirmation_url
/         td = form.active
/         td = link_to 'Show', form
/         td = link_to 'Edit', edit_form_path(form)
/         td = link_to 'Destroy', form, method: :delete, data: { confirm: 'Are you sure?' }

app/views/forms/new.html.slim
header.header
  h1 New Form
  h2 Supervise a new form

main
  = render 'form', form: @form

.actions
  = link_to 'Back', forms_path

app/views/forms/show.html.slim
p#notice = notice

p
  strong Name:
  = @form.name

p
  strong URL:
  = @form.url

p
  strong Confirmation URL:
  = @form.confirmation_url

p
  strong Active:
  = @form.active

p
  strong Trigger frequency:
  = @form.trigger_frequency

= link_to 'Edit', edit_form_path(@form)
= link_to 'Back', forms_path

app/views/layouts/application.html.slim
doctype html
html lang='en'
  head
    meta charset='utf-8'
    meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'
    meta http-equiv='x-ua-compatible' content='ie=edge'

    title FormSupervisor
    = csrf_meta_tags

    = stylesheet_link_tag fingerprinted_asset('application'), media: 'all'
    = javascript_include_tag fingerprinted_asset('application')
  body class='#{controller_name.demodulize} #{action_name}'
    = yield

app/views/validation_patterns/_form.html.slim
= form_for(validation_pattern) do |f|
  - if validation_pattern.errors.any?
    #error_explanation
      h2
        = pluralize(validation_pattern.errors.count, "error")
        |  prohibited this validation_pattern from being saved:

      ul
        - validation_pattern.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name

    = f.submit

app/views/validation_patterns/edit.html.slim
header.header
  h1 Editing Validation Pattern
  h2

main
  = render 'form', validation_pattern: @validation_pattern

.actions
  = link_to 'Show', @validation_pattern
  = link_to 'Back', validation_patterns_path

app/views/validation_patterns/index.html.slim
p#notice
  = notice
h1
  | Validation Patterns
table
  thead
    tr
      th
        | Name
      th[colspan="3"]
  tbody
    - @validation_patterns.each do |validation_pattern|
      tr
        td
          = validation_pattern.name
        td
          = link_to 'Show', validation_pattern
        td
          = link_to 'Edit', edit_validation_pattern_path(validation_pattern)
        td
          = link_to 'Destroy', validation_pattern, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Validation Pattern', new_validation_pattern_path

app/views/validation_patterns/new.html.slim
header.header
  h1 New Validation Pattern
  h2 Create a way to validate forms

main
  = render 'form', validation_pattern: @validation_pattern

.actions
  = link_to 'Back', validation_patterns_path

app/views/validation_patterns/show.html.slim
p#notice = notice

main
  | Name: #{@validation_pattern.name}

.actions
  = link_to 'Edit', edit_validation_pattern_path(@validation_pattern)
  = link_to 'Back', validation_patterns_path